/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockRouterCcipSol from "./MockRouter_CCIP.sol";
export type { mockRouterCcipSol };
export type { MockBnMToken } from "./MockBnMToken";
